// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcKsCzBCot1FoGbFmt-wq1w-FDESSVlHk',
    appId: '1:683828119896:web:3412851ba290a52953bd2d',
    messagingSenderId: '683828119896',
    projectId: 'aquacare-55ba6',
    authDomain: 'aquacare-55ba6.firebaseapp.com',
    storageBucket: 'aquacare-55ba6.firebasestorage.app',
    measurementId: 'G-ZMYQWCF0RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jelOEZhn4mMjOsq3vJ7sn_EDrd4qqNw',
    appId: '1:683828119896:android:836d327873b5d0ef53bd2d',
    messagingSenderId: '683828119896',
    projectId: 'aquacare-55ba6',
    storageBucket: 'aquacare-55ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzeAya5oRjn_DspMsY3xkzP71_4zjwrr0',
    appId: '1:683828119896:ios:2d293115c060655853bd2d',
    messagingSenderId: '683828119896',
    projectId: 'aquacare-55ba6',
    storageBucket: 'aquacare-55ba6.firebasestorage.app',
    iosBundleId: 'com.example.ledgerly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzeAya5oRjn_DspMsY3xkzP71_4zjwrr0',
    appId: '1:683828119896:ios:2d293115c060655853bd2d',
    messagingSenderId: '683828119896',
    projectId: 'aquacare-55ba6',
    storageBucket: 'aquacare-55ba6.firebasestorage.app',
    iosBundleId: 'com.example.ledgerly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcKsCzBCot1FoGbFmt-wq1w-FDESSVlHk',
    appId: '1:683828119896:web:686d679b8cae448953bd2d',
    messagingSenderId: '683828119896',
    projectId: 'aquacare-55ba6',
    authDomain: 'aquacare-55ba6.firebaseapp.com',
    storageBucket: 'aquacare-55ba6.firebasestorage.app',
    measurementId: 'G-431FQJCMJD',
  );
}
