// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhzaYs4_mU6sio4M9TgeHHACkf1BhKwc',
    appId: '1:704021297243:web:db933170329a125eb7677e',
    messagingSenderId: '704021297243',
    projectId: 'ledgerly-c051a',
    authDomain: 'ledgerly-c051a.firebaseapp.com',
    storageBucket: 'ledgerly-c051a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPK_9W9DY-Z70YAAoLb26PEbMPMQ-WMM',
    appId: '1:704021297243:android:5bc23d13dc9790e7b7677e',
    messagingSenderId: '704021297243',
    projectId: 'ledgerly-c051a',
    storageBucket: 'ledgerly-c051a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxXDmIj_63TBnEL5-ww3F2S1l8GikWl0',
    appId: '1:704021297243:ios:62d583f58ace6b2ab7677e',
    messagingSenderId: '704021297243',
    projectId: 'ledgerly-c051a',
    storageBucket: 'ledgerly-c051a.firebasestorage.app',
    iosBundleId: 'com.example.ledgerly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxXDmIj_63TBnEL5-ww3F2S1l8GikWl0',
    appId: '1:704021297243:ios:62d583f58ace6b2ab7677e',
    messagingSenderId: '704021297243',
    projectId: 'ledgerly-c051a',
    storageBucket: 'ledgerly-c051a.firebasestorage.app',
    iosBundleId: 'com.example.ledgerly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyhzaYs4_mU6sio4M9TgeHHACkf1BhKwc',
    appId: '1:704021297243:web:9ebef30b1279b195b7677e',
    messagingSenderId: '704021297243',
    projectId: 'ledgerly-c051a',
    authDomain: 'ledgerly-c051a.firebaseapp.com',
    storageBucket: 'ledgerly-c051a.firebasestorage.app',
  );

}